name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install tree
        run: sudo apt-get install tree
      - name: Generate folder structure
        run: tree --dirsfirst --noreport -F --charset ascii -T " " -o README.md && sed -i 's/^/    /' test.md
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add test.md
          git commit -m "Update README"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with: 
          github_token: {{ secrets.GITHUB_TOKEN }}
